/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Overview"
    },
    {
      type: "doc",
      id: "actions",
      label: "Action Targeting"
    },
    {
      type: "doc",
      id: "segments",
      label: "Action Segments"
    },
    {
      type: "doc",
      id: "realtime",
      label: "Realtime Orchestration"
    },
    {
      type: "category",
      label: "Integrations",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "integrations",
        },
      ],
    },
    {
      type: "category",
      label: "Program Examples",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "program-examples",
        },
      ],
    },
    {
      type: "doc",
      id: "events",
      label: "Event Data Sources"
    },
  ],
  actionHubApi: [
  {
    type: "category",
    label: "ActionHub REST API",
    link: {
      type: "generated-index",
      title: "ActionHub API",
      description:
        "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
      slug: "/category/petstore-api",
    },
    items: require("./docs/api/sidebar.js"),
  }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
